// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Patients struct {
	ID       int32  `json:"id"`
	FullName string `json:"full_name"`
	// Age in years
	Age *int `json:"age"`
	// Values: Male, Female, Non-binary, etc.
	Gender *string `json:"gender"`
	// Email or phone number for communication
	ContactInfo string `json:"contact_info"`
	// Reference to assigned device
	AssignedDeviceID *int32 `json:"assigned_device_id"`
	// Record creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Record last updated timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type WearableDevices struct {
	ID         int32  `json:"id"`
	DeviceName string `json:"device_name"`
	// E.g., Heart Rate Monitor, Pulse Oximeter
	DeviceType string `json:"device_type"`
	// Reference to the assigned patient
	AssignedPatientID *int32 `json:"assigned_patient_id"`
	// Unique serial number of the device
	SerialNumber string `json:"serial_number"`
	// Country code where the device is registered
	CountryCode *int32 `json:"country_code"`
	// Record creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Record last updated timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
}
